import type { GitInsights, ProjectScan } from "../types.js";

const DRAFT_BANNER = `<!-- DUOSHE-DRAFT: this section was auto-generated by \`duoshe init\`.
     Review and edit freely. Add <!-- USER-CONFIRMED --> on a line above any
     paragraph you want \`duoshe rescan\` to preserve. -->`;

function bullets(lines: string[]): string {
  if (lines.length === 0) return "_(none detected)_";
  return lines.map((l) => `- ${l}`).join("\n");
}

function mermaidId(raw: string): string {
  const cleaned = raw.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  return cleaned.length === 0 ? "node" : cleaned;
}

function mermaidLabel(raw: string): string {
  return raw.replaceAll('"', '\\"');
}

function relTime(days: number): string {
  if (days < 1) return "today";
  if (days < 30) return `${Math.round(days)} day(s) ago`;
  if (days < 365) return `${Math.round(days / 30)} month(s) ago`;
  return `${(days / 365).toFixed(1)} year(s) ago`;
}

export function renderProjectMd(opts: {
  projectName: string;
  scan: ProjectScan;
  git: GitInsights;
}): string {
  const { projectName, scan, git } = opts;
  const stacks = scan.stacks.map(
    (s) =>
      `**${s.language}**${s.framework ? ` (${s.framework})` : ""}` +
      `${s.packageManager ? ` — package manager: \`${s.packageManager}\`` : ""}` +
      ` — manifest: \`${s.manifestFile}\``,
  );
  const dirs = scan.topDirs.map(
    (d) => `\`${d.name}/\` — ${d.guessedRole ?? "purpose unclear"} (${d.fileCount} files)`,
  );
  const entries = scan.entryPoints.map((e) => `\`${e.path}\` (${e.kind})`);
  const hot =
    git.hotFiles?.map((f) => `\`${f.path}\` — ${f.commits} commits in last 30 days`) ?? [];

  return `# ${projectName}

${DRAFT_BANNER}

## Overview

_One or two sentences: what is this project for? Who uses it?_

## Tech stack

${bullets(stacks)}

## Project shape

- Total files: ${scan.totalFiles}
- Source files: ${scan.totalSourceFiles}
- Top-level directories:

${bullets(dirs)}

## Entry points

${bullets(entries)}

## Repository

${
  git.isGitRepo
    ? [
        git.remoteUrl ? `- Remote: ${git.remoteUrl}` : "- Remote: _(local only)_",
        git.defaultBranch ? `- Default branch: \`${git.defaultBranch}\`` : "",
        git.ageDays != null ? `- First commit: ${relTime(git.ageDays)}` : "",
        git.contributorCount != null
          ? `- Contributors (all-time): ${git.contributorCount}`
          : "",
      ]
        .filter(Boolean)
        .join("\n")
    : "_Not a git repository._"
}

## Hot spots (last 30 days)

${bullets(hot)}

## Conventions to remember

_Add team or project conventions an AI should know: naming style, lint rules,
banned APIs, branching model, anything weird about this codebase._

- ...

## Constraints and gotchas

_Things an AI must NOT do. Compatibility requirements. Performance budgets._

- ...

---

_Generated by DuoShe ${scan.scannedAt}. Search memory: \`duoshe search "<query>"\`._
`;
}

export function renderCodeMapMd(opts: {
  projectName: string;
  scan: ProjectScan;
  git: GitInsights;
}): string {
  const { projectName, scan, git } = opts;
  const stackLines = scan.stacks.map(
    (s) =>
      `\`${s.manifestFile}\` -> ${s.language}${s.framework ? `/${s.framework}` : ""}${
        s.packageManager ? ` (${s.packageManager})` : ""
      }`,
  );
  const entryLines = scan.entryPoints.map((e) => `\`${e.path}\` (${e.kind})`);
  const dirLines = scan.topDirs.map(
    (d) => `| \`${d.name}/\` | ${d.guessedRole ?? "purpose unclear"} | ${d.fileCount} |`,
  );
  const hotLines =
    git.hotFiles?.map((f) => `\`${f.path}\` — ${f.commits} commits in last 30 days`) ?? [];
  const graphDirs = scan.topDirs.slice(0, 10);
  const graphEntries = scan.entryPoints.slice(0, 8);
  const graphLines = [
    `  root["${mermaidLabel(projectName)}"]`,
    ...graphDirs.map((d) => `  root --> ${mermaidId(d.name)}["${mermaidLabel(`${d.name}/`)}"]`),
    ...graphEntries.map((e, i) => {
      const first = e.path.split("/")[0] ?? "root";
      const parent = scan.topDirs.some((d) => d.name === first) ? mermaidId(first) : "root";
      return `  ${parent} --> entry${i}["${mermaidLabel(e.path)}"]`;
    }),
  ];

  return `# Code Map

${DRAFT_BANNER}

> A compact map of the repository shape for AI agents. Keep this practical:
> entry points, ownership boundaries, and files that deserve extra caution.

## System graph

\`\`\`mermaid
flowchart TD
${graphLines.join("\n")}
\`\`\`

## Runtime and stack signals

${bullets(stackLines)}

## Entry points

${bullets(entryLines)}

## Directory map

| Path | Likely role | Files |
| --- | --- | ---: |
${dirLines.length === 0 ? "| _(none)_ | _(none detected)_ | 0 |" : dirLines.join("\n")}

## Hot files

${bullets(hotLines)}

## Human notes

_Use \`duoshe guide\` to add project-specific routing notes, ownership rules, and areas AI agents should inspect first._

---

_Generated by DuoShe ${scan.scannedAt}. Refresh with \`duoshe rescan\`._
`;
}

export function renderDecisionsMd(): string {
  return `# Decisions

${DRAFT_BANNER}

> Architectural and design decisions worth remembering across AI sessions.
> Use \`duoshe remember "..." --type decision\` to add a candidate,
> then \`duoshe publish <id>\` to record it here.

Each entry should answer: **what**, **why**, **alternatives considered**, **status**.

---

_(no decisions recorded yet)_
`;
}

export function renderTroubleshootingMd(): string {
  return `# Troubleshooting

${DRAFT_BANNER}

> Bugs, gotchas, and fixes — so the next AI session (or you) doesn't re-debug.
> Use \`duoshe remember "..." --type troubleshooting\`.

Each entry should answer: **symptom**, **root cause**, **fix**, **how to verify**, **related files**.

---

_(no troubleshooting entries yet)_
`;
}

export function renderModulesMd(opts: { scan: ProjectScan }): string {
  const dirs = opts.scan.topDirs.map(
    (d) =>
      `### \`${d.name}/\`\n\n` +
      `**Role:** ${d.guessedRole ?? "_unclear — please describe_"}\n\n` +
      `**Owns:** _(what does this module own?)_\n\n` +
      `**Does NOT own:** _(what should NEVER live here?)_\n\n` +
      `**Depends on:** _(internal/external dependencies)_\n`,
  );

  return `# Modules

${DRAFT_BANNER}

> Module boundaries — what each part owns and (importantly) does NOT own.
> The "does NOT own" line is the most valuable for AI agents.

${
  dirs.length === 0
    ? "_No top-level directories detected._"
    : dirs.join("\n---\n\n")
}
`;
}

export function renderTodoMd(): string {
  return `# TODO

${DRAFT_BANNER}

> Current tasks and what's coming next. Lightweight — for daily working memory.

## In progress

- _(nothing in progress)_

## Up next

- _(nothing queued)_

## Backlog

- _(empty)_
`;
}
