import { readFileSync, writeFileSync } from "node:fs";
import type { Command } from "commander";
import kleur from "kleur";
import { analyzeGraph, renderMermaid } from "../../skills/graph/index.js";
import { readConfig } from "../../core/vault/config.js";
import { vaultExists, vaultPathsFor } from "../../core/vault/index.js";
import { log } from "../log.js";

const GRAPH_START = "<!-- BEGIN DUOSHE-GRAPH -->";
const GRAPH_END = "<!-- END DUOSHE-GRAPH -->";

type GraphOptions = {
  output?: "codemap" | "stdout";
  hot?: boolean;
};

function mergeGraphBlock(existing: string, block: string): string {
  if (existing.includes(GRAPH_START)) {
    const before = existing.slice(0, existing.indexOf(GRAPH_START)).trimEnd();
    const after = existing.slice(existing.indexOf(GRAPH_END) + GRAPH_END.length).trimStart();
    return after ? `${before}\n\n${block}\n\n${after}` : `${before}\n\n${block}\n`;
  }
  return existing.trimEnd() ? `${existing.trimEnd()}\n\n${block}\n` : `${block}\n`;
}

async function runGraph(opts: GraphOptions): Promise<void> {
  const root = process.cwd();

  if (!vaultExists(root)) {
    log.err("No .duoshe/ found. Run `duoshe init` first.");
    process.exit(1);
  }

  const paths = vaultPathsFor(root);
  const cfg = readConfig(paths.config);

  if (cfg && !cfg.enabledSkills.includes("graph")) {
    log.warn(`The "graph" skill is not enabled.`);
    log.raw(`  Enable it first: ${kleur.cyan("duoshe skill enable graph")}`);
    log.raw(`  Or list skills:  ${kleur.cyan("duoshe skill list")}`);
    process.exit(1);
  }

  log.step("Analyzing import dependencies");
  const start = Date.now();
  const analysis = analyzeGraph(root);
  const elapsed = Date.now() - start;

  log.ok(`Scanned ${analysis.files.length} source file(s), found ${analysis.edges.length} import edge(s) (${elapsed}ms)`);

  if (analysis.cycles.length > 0) {
    log.warn(`${analysis.cycles.length} cyclic dependency chain(s) detected:`);
    for (const cycle of analysis.cycles.slice(0, 5)) {
      log.raw(`  ${kleur.yellow(cycle.join(" → "))}`);
    }
    if (analysis.cycles.length > 5) {
      log.raw(`  ${kleur.gray(`... and ${analysis.cycles.length - 5} more`)}`);
    }
  } else {
    log.ok("No cyclic dependencies found");
  }

  if (opts.hot !== false && analysis.hotNodes.length > 0) {
    log.blank();
    log.raw(kleur.bold("Hot modules (most imported):"));
    for (const { file, inDegree } of analysis.hotNodes.slice(0, 5)) {
      log.raw(`  ${kleur.cyan(String(inDegree).padStart(3))}  ${file}`);
    }
  }

  const mermaid = renderMermaid(analysis);

  if ((opts.output ?? "codemap") === "stdout") {
    log.blank();
    log.raw(mermaid);
    return;
  }

  const block = `${GRAPH_START}\n## Import Dependency Graph\n\n\`\`\`mermaid\n${mermaid}\n\`\`\`\n\n_Generated by \`duoshe graph\` on ${new Date().toISOString()}_\n${GRAPH_END}`;

  let existing: string;
  try {
    existing = readFileSync(paths.codeMap, "utf8");
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
    existing = "";
  }

  writeFileSync(paths.codeMap, mergeGraphBlock(existing, block), "utf8");
  log.blank();
  log.ok(`Graph written to ${kleur.cyan(".duoshe/CODEMAP.md")}`);
}

export function registerGraphCommand(program: Command): void {
  program
    .command("graph")
    .description(
      `analyze import dependencies in source files and write a Mermaid graph to .duoshe/CODEMAP.md (requires skill "graph" to be enabled)`,
    )
    .option("--output <mode>", "where to write: codemap (default) | stdout", "codemap")
    .option("--no-hot", "skip hot-module listing")
    .action(async (opts: GraphOptions) => {
      try {
        await runGraph(opts);
      } catch (err) {
        log.err(err instanceof Error ? err.message : String(err));
        process.exit(1);
      }
    });
}
